game_action="GAME_ACTION"
game_adventure="GAME_ADVENTURE"
game_arcade="GAME_ARCADE"
game_board="GAME_BOARD"
game_card="GAME_CARD"
game_casino="GAME_CASINO"
game_casual="GAME_CASUAL"
game_educational="GAME_EDUCATIONAL"
game_music="GAME_MUSIC"
game_puzzle="GAME_PUZZLE"
game_racing="GAME_RACING"
game_role_playing="GAME_ROLE_PLAYING"
game_simulation="GAME_SIMULATION"
game_sports="GAME_SPORTS"
game_strategy="GAME_STRATEGY"
game_trivia="GAME_TRIVIA"
game_word="GAME_WORD"
family_action_adventure="FAMILY_ACTION"
family_brain_games="FAMILY_BRAINGAMES"

game_catagories = []
game_catagories.append(game_action)
game_catagories.append(game_adventure)
game_catagories.append(game_arcade)
game_catagories.append(game_board)
game_catagories.append(game_card)
game_catagories.append(game_casino)
game_catagories.append(game_casual)
game_catagories.append(game_educational)
game_catagories.append(game_music)
game_catagories.append(game_puzzle)
game_catagories.append(game_racing)
game_catagories.append(game_role_playing)
game_catagories.append(game_role_playing)
game_catagories.append(game_simulation)
game_catagories.append(game_sports)
game_catagories.append(game_strategy)
game_catagories.append(game_trivia)
game_catagories.append(game_word)
game_catagories.append(family_action_adventure)
game_catagories.append(family_brain_games)